image: node:8

before_script:
  - apt-get update && apt-get install python-dev python-pip zip jq -y
  - pip install awscli --upgrade --user
  - export PATH=~/.local/bin:$PATH
  - npm i -g yarn
stages:
  - deploy

variables:
  S3_BUCKET: codebox-backend

deploy_prettier:
  variables:
    SERVICE_NAME: prettier
    LAMBDA_ROLE: 166000737765:role/service-role/codebox-prettier-role-9kiko2nz
  stage: deploy

  only:
  - master

  script:
  - cd $SERVICE_NAME &&
    yarn &&
    npx parcel build
      --no-cache
      --no-minify
      --no-source-maps
      -t node
      --bundle-node-modules
      -d ./dist -o lambda.js lambda.js
  - cd dist && zip -r $SERVICE_NAME.zip . # -x \*.pyc *.git*
  - aws s3 cp $SERVICE_NAME.zip s3://$S3_BUCKET/$SERVICE_NAME.zip
  - aws lambda update-function-code
      --region eu-west-1
      --function-name codebox-$SERVICE_NAME
      --zip-file fileb://$SERVICE_NAME.zip ||
    aws lambda create-function
      --region eu-west-1
      --function-name codebox-$SERVICE_NAME
      --runtime nodejs10.x
      --role arn:aws:iam::$LAMBDA_ROLE
      --handler lambda.default
      --code S3Bucket=$S3_BUCKET,S3Key=$SERVICE_NAME.zip
      --memory-size 1024

  environment:
    name: master
