version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd rollup
      - yarn
      - cd ..
  build:
    commands:
      - cd rollup
      - npx parcel build
        --no-cache
        --no-minify
        --no-source-maps
        --bundle-node-modules
        -t node
        -d ./dist
        -o lambda.js
        src/lambda.js
      - npx sls deploy
